# Generated by Django 5.2.5 on 2025-08-16 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("location", models.CharField(help_text="Место", max_length=128, verbose_name="Место")),
                ("start_time", models.TimeField(help_text="Время", verbose_name="Время")),
                ("action", models.CharField(help_text="Действие", max_length=255, verbose_name="Действие")),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False, help_text="Признак приятной привычки", verbose_name="Признак приятной привычки"
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Периодичность от 1 до 7", verbose_name="Периодичность"
                    ),
                ),
                (
                    "rewards",
                    models.CharField(
                        blank=True, help_text="Награды", max_length=255, null=True, verbose_name="Награды"
                    ),
                ),
                (
                    "time_to_complete",
                    models.PositiveIntegerField(
                        help_text="Время выполнения от 0 до 120 секунд", verbose_name="Время выполнения"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Публичная привычка", verbose_name="Публичная привычка"
                    ),
                ),
                (
                    "related_habits",
                    models.ForeignKey(
                        blank=True,
                        help_text="Связанные привычки",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="Связанные привычки",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Пользователь",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
