# Generated by Django 5.2.5 on 2025-08-17 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_alter_habit_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={"ordering": ["-id"], "verbose_name": "Привычка", "verbose_name_plural": "Привычки"},
        ),
    ]
