# Generated by Django 5.2.5 on 2025-08-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="last_notification",
            field=models.DateTimeField(
                blank=True,
                help_text="Время последнего отправленного уведомления",
                null=True,
                verbose_name="Последнее уведомление",
            ),
        ),
    ]
