# Generated by Django 5.2.5 on 2025-08-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_habit_last_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="tg_chat_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите telegram чат ID",
                max_length=50,
                null=True,
                verbose_name="Telegram чат ID",
            ),
        ),
    ]
