# Generated by Django 5.2.5 on 2025-08-17 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0005_habit_tg_chat_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="tg_chat_id",
        ),
    ]
