# Generated by Django 5.2.5 on 2025-08-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0006_remove_habit_tg_chat_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="next_notification",
            field=models.DateTimeField(
                blank=True, help_text="Когда отправить следующий раз", null=True, verbose_name="Следующее уведомление"
            ),
        ),
    ]
